'use strict';
const courses = [
  {name:'생성형 AI 활용',title:'생성형 AI, 기초부터 실무 활용까지',intro:'질문하는 방법부터 글쓰기와 자료 정리까지. 일상과 업무에 AI를 연결합니다.',target:'AI 입문자 · 모든 교육 대상',steps:['생성형 AI의 기본 개념과 사용 방법','원하는 답변을 얻는 질문과 프롬프트 작성','글쓰기, 요약, 번역과 자료 정리','이메일, 안내문, 기획안 초안 작성','AI 답변 확인과 정보 입력 시 유의사항'],result:'개인별 프롬프트 모음과 목적에 맞는 문서 초안',book:'생성형 AI\n실무 활용 가이드'},
  {name:'AI 이미지 제작',title:'AI 이미지, 생각을 시각 자료로',intro:'머릿속 아이디어를 이미지로. 수업 자료부터 홍보 콘텐츠까지 직접 만듭니다.',target:'교육자 · 홍보 담당자 · 콘텐츠 제작자',steps:['이미지 생성 도구의 기본 사용 방법','구도, 스타일, 색감을 설명하는 프롬프트','이미지 생성과 수정','수업 자료, 홍보 이미지, 썸네일 제작','결과물의 이용 조건 확인'],result:'교육용 이미지 또는 홍보용 시각 자료',book:'AI 이미지\n제작 가이드'},
  {name:'AI 영상 제작',title:'AI 영상, 기획부터 짧은 콘텐츠 완성까지',intro:'아이디어를 대본으로, 장면을 영상으로. 나만의 콘텐츠를 완성하는 과정입니다.',target:'영상 입문자 · 교육자 · 홍보 담당자',steps:['영상 목적과 시청 대상 설정','AI를 활용한 대본과 장면 구성','이미지·영상 생성','자막, 음성, 장면 편집','결과물 검토와 게시용 파일 준비'],result:'짧은 교육 영상 또는 홍보 영상',book:'AI 영상\n제작 가이드'},
  {name:'AI 업무자동화',title:'AI 업무자동화, 반복 업무 줄이기',intro:'매번 반복하는 업무를 돌아보고, AI와 도구를 연결해 작업 흐름을 바꿉니다.',target:'기업 실무자 · 교육자 · 공무원',steps:['자동화할 업무 찾기','입력 자료와 작업 단계 정리','AI를 활용한 문서·자료 처리','도구 연결과 자동화 흐름 구성','결과 확인과 오류 대응'],result:'업무 목적에 맞춘 자동화 흐름 또는 실습 예제',book:'AI 업무자동화\n실무 가이드'}
];
const audiences=[['시니어','SENIORS','AI가 처음이어도 괜찮아요. 생활 속 활용부터 차근차근.'],['기업','BUSINESS','우리 팀의 업무에 연결하는 AI. 문서부터 자동화까지.'],['교육자','EDUCATORS','수업 준비부터 학습 자료까지. 교육의 가능성을 넓히세요.'],['공무원','PUBLIC SECTOR','문서 초안과 자료 정리. 행정 업무에 필요한 활용부터.']];
const groups=[['교육 소개',[['교육 방향','#about'],['강사 소개','#instructor'],...audiences.map((a,i)=>[a[0]+' AI 교육','#audience-'+i]),['교육 진행 방식','#method']]],['강의 안내',[['전체 강의','#courses'],...courses.map((c,i)=>[c.name,'course',i]),['강의 일정','info','schedule'],['강의 신청','apply',0]]],['맞춤 강연',[['맞춤 강연 안내','#custom'],...['시니어·복지기관 강연','기업·단체 강연','학교·교육기관 강연','공공기관·공무원 강연'].map((s,i)=>[s,'audience',i]),['주제·시간별 구성','info','custom'],['강연 문의','inquiry']]],['전자책 스토어',[['전체 전자책','#books'],...courses.map((c,i)=>[c.name+' e-book','book',i]),['전자책 미리보기','info','preview'],['구매 내역·다운로드','info','download']]],['고객지원',[['공지사항','info','notice'],['자주 묻는 질문','#support'],['수강 준비 안내','info','prepare'],['신청 조회·변경','info','change'],['결제·다운로드 도움말','info','download'],['취소·환불 안내','info','refund'],['일반 문의','info','contact']]]];
document.querySelector('#navigation').innerHTML=groups.map(([name,items],i)=>`<div class="nav-group"><button class="nav-trigger" aria-expanded="false" aria-controls="submenu-${i}">${name}<span aria-hidden="true">⌄</span></button><div class="submenu" id="submenu-${i}">${items.map(([label,type,value])=>type.startsWith('#')?`<a href="${type}">${label}</a>`:`<button data-${type}="${value??''}">${label}</button>`).join('')}</div></div>`).join('');
document.querySelector('#audiences').innerHTML=audiences.map(([name,en,desc],i)=>`<article class="audience" id="audience-${i}"><span class="audience-number">0${i+1} / ${en}</span><h3>${name}</h3><p>${desc}</p><button data-audience="${i}">${name} 맞춤 교육 문의 <span aria-hidden="true">↗</span></button></article>`).join('');
document.querySelector('#course-list').innerHTML=courses.map((c,i)=>`<article class="course"><span class="course-number">0${i+1}</span><div><h3>${c.name}</h3><p>${c.intro}</p><div class="meta"><span>${c.target}</span><span>기초부터 · 맞춤 구성</span></div></div><div class="course-actions"><button data-course="${i}">강의 내용 보기 ↗</button><button data-apply="${i}">강의 신청 상담 ↗</button><button data-book="${i}">관련 e-book 안내 ↗</button><small>일정·방식 상담 후 안내</small></div></article>`).join('');
document.querySelector('#book-list').innerHTML=courses.map((c,i)=>`<article class="book"><div class="book-index"><span>GUIDE 0${i+1} / PDF</span><span>출간 준비 중</span></div><h3>${c.book.replace('\n','<br>')}</h3><p>${c.intro.split('. ')[0].replace(/\.$/, '')}.</p><button data-book="${i}">전자책 안내 보기 ↗</button></article>`).join('');
const faqs=[['AI를 처음 사용해도 수강할 수 있나요?','입문자를 위한 기초 내용을 포함하여 교육을 구성합니다. 현재 사용 경험과 배우고 싶은 내용을 알려주시면 적합한 과정을 안내해 드립니다.'],['시니어 대상 교육은 어떻게 진행하나요?','쉬운 질문, 글쓰기, 정보 정리처럼 생활에 가까운 주제를 중심으로 안내합니다. 참여자의 기기 사용 경험과 수준을 상담할 때 함께 알려주세요.'],['기업이나 기관에 맞춘 교육도 가능한가요?','교육 대상, 업무 목적, 희망 주제와 인원을 바탕으로 내용을 상담합니다. 방문 또는 온라인 진행 가능 여부, 시간과 비용은 개별 안내합니다.'],['노트북이나 유료 AI 계정이 필요한가요?','과정에서 사용하는 도구와 실습에 따라 준비물이 달라집니다. 교육 방식이 정해진 뒤 필요한 기기와 계정을 안내합니다. 상담 전에 유료 계정을 먼저 구매하실 필요는 없습니다.'],['전자책은 어떻게 구매하고 다운로드하나요?','현재 전자책은 출간 준비 중입니다. 원고와 판매 조건이 확정되면 가격, 미리보기, 구매 및 다운로드 방법을 안내합니다. 현재 사이트에서는 결제를 받지 않습니다.'],['신청 변경이나 기타 문의는 어디로 하나요?','010-5213-4478 또는 e_ikenkon@hanmail.net으로 문의해 주세요. 이 사이트의 상담 양식은 이메일 작성용이며, 실제 발송 후 담당자와 상담하여 일정을 확정합니다.']];
document.querySelector('#faq-list').innerHTML=faqs.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('');
const modal=document.querySelector('#modal'),content=document.querySelector('#modal-content');
function show(html){content.innerHTML=html;if(!modal.open)modal.showModal();document.body.classList.add('modal-open');modal.scrollTop=0;}
function closeMenu(){document.querySelectorAll('.nav-group').forEach(g=>{g.classList.remove('is-open');g.querySelector('button').setAttribute('aria-expanded','false')});}
document.querySelector('.close-modal').addEventListener('click',()=>modal.close());
modal.addEventListener('close',()=>document.body.classList.remove('modal-open'));
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
document.querySelector('.menu-toggle').addEventListener('click',e=>{const opened=document.querySelector('#navigation').classList.toggle('mobile-open');e.currentTarget.setAttribute('aria-expanded',String(opened));if(!opened)closeMenu()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();document.querySelector('#navigation').classList.remove('mobile-open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}});
document.addEventListener('click',e=>{
 const trigger=e.target.closest('.nav-trigger');if(trigger){const group=trigger.parentElement,open=!group.classList.contains('is-open');closeMenu();group.classList.toggle('is-open',open);trigger.setAttribute('aria-expanded',String(open));return}
 if(!e.target.closest('.nav-group'))closeMenu();
 const btn=e.target.closest('[data-course],[data-book],[data-apply],[data-inquiry],[data-audience],[data-info]');
 if(btn){closeMenu();if(btn.hasAttribute('data-course'))showCourse(Number(btn.dataset.course));else if(btn.hasAttribute('data-book'))showBook(Number(btn.dataset.book));else if(btn.hasAttribute('data-apply'))showForm('강의 신청 상담',Number(btn.dataset.apply));else if(btn.hasAttribute('data-audience'))showForm('맞춤 강연 문의',0,Number(btn.dataset.audience));else if(btn.hasAttribute('data-inquiry'))showForm('맞춤 강연 문의');else showInfo(btn.dataset.info)}
 if(btn||e.target.closest('#navigation a')){document.querySelector('#navigation').classList.remove('mobile-open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}
});
function showCourse(i){const c=courses[i];show(`<h2 id="modal-title">${c.title}</h2><p>${c.intro}</p><p class="notice">교육 구성 예시입니다. 실제 내용·난이도·일정·장소·진행 방식·비용은 상담 후 확정합니다.</p><h3>이런 분께 추천합니다</h3><p>${c.target}</p><h3>함께 배우는 내용</h3><ol>${c.steps.map(s=>`<li>${s}</li>`).join('')}</ol><h3>실습 결과물 예시</h3><p>${c.result}</p><div class="actions"><button class="button" data-apply="${i}">강의 신청 상담 ↗</button><button class="text-button" data-book="${i}">관련 e-book 안내 ↗</button></div>`)}
function showBook(i){const c=courses[i];show(`<h2 id="modal-title">${c.book.replace('\n',' ')}</h2><p class="notice">출간 준비 중 · 현재 구매할 수 없습니다.</p><p>${c.name} 학습을 돕는 PDF 활용 가이드를 준비하고 있습니다. 원고 확정 후 목차, 미리보기, 가격과 판매 일정을 안내합니다.</p><p>현재 결제를 받거나 구매자 정보를 수집하지 않습니다.</p><div class="actions"><button class="button" data-course="${i}">관련 강의 살펴보기 ↗</button><a class="text-button" href="mailto:e_ikenkon@hanmail.net?subject=${encodeURIComponent(c.name+' 전자책 문의')}">이메일로 문의 ↗</a></div>`)}
const info={schedule:['강의 일정','현재 공개된 모집 회차는 없습니다. 희망 교육 분야와 일정을 알려주시면 상담 후 가능한 일정과 진행 방식을 안내합니다.'],custom:['주제·시간별 교육 구성','생성형 AI, 이미지, 영상, 업무자동화 중 필요한 분야를 선택해 주세요. 교육 대상, 참여자의 수준과 희망 시간을 바탕으로 구체적인 구성을 상담합니다.'],preview:['전자책 미리보기','전자책은 출간 준비 중이며 아직 공개된 미리보기가 없습니다. 원고와 목차가 확정되면 이곳에서 안내합니다.'],download:['구매 내역·다운로드 안내','현재 전자책 판매와 온라인 결제는 시작되지 않았습니다. 조회 가능한 온라인 주문이나 다운로드 파일이 없습니다. 기존에 별도로 안내받은 구매 건은 대표 연락처로 문의해 주세요.'],notice:['공지사항','현재 등록된 공지사항이 없습니다. 교육 일정과 전자책 출간 소식이 확정되면 안내합니다.'],prepare:['수강 준비 안내','교육 과정이 확정되면 실습에 필요한 기기, AI 도구와 계정을 안내합니다. 상담 시 노트북이나 스마트폰 사용 가능 여부를 알려주세요.'],change:['신청 조회·변경','이메일 또는 전화로 상담하신 강의의 이름과 희망 변경 내용을 알려주세요. 담당자 확인 후 변경 가능 여부를 안내합니다.'],refund:['구매·환불 안내','현재 사이트에서는 결제와 상품 판매를 진행하지 않습니다. 교육 비용이나 전자책 구매 조건이 확정되면 결제 전에 취소·환불 기준을 안내합니다. 이미 별도 계약이나 구매 안내를 받으셨다면 담당자에게 해당 건을 문의해 주세요.'],privacy:['개인정보 안내','이 페이지의 상담 양식에 입력한 내용은 사이트 서버에 저장되지 않습니다. 이메일 작성 버튼을 누르면 선택한 메일 앱으로 내용이 전달되며, 실제 발송 여부는 이용자가 결정합니다. 입력값은 브라우저 저장소에 보관하지 않습니다. 이메일로 보내는 개인정보의 처리 기준은 발송 전에 담당자에게 문의해 주세요.'],terms:['사이트 이용 안내','이 사이트는 일의다음의 AI 교육과 전자책 준비 소식을 안내합니다. 교육 커리큘럼은 구성 예시이며 실제 내용, 일정, 비용은 개별 상담으로 확정합니다. 온라인 상담 양식 작성만으로 신청이 접수되거나 수강이 확정되지 않습니다.'],contact:['일반 문의','교육과 전자책에 관해 궁금한 내용을 전화 또는 이메일로 문의해 주세요. 전화 010-5213-4478 · 이메일 e_ikenkon@hanmail.net']};
function showInfo(key){const [title,body]=info[key]||info.contact;show(`<h2 id="modal-title">${title}</h2><p>${body}</p><div class="actions"><a class="button" href="tel:01052134478">전화로 문의하기 ↗</a><a class="text-button" href="mailto:e_ikenkon@hanmail.net">이메일 문의 ↗</a></div>`)}
function showForm(title,index=0,audience=-1){show(`<h2 id="modal-title">${title}</h2><p>배우고 싶은 주제와 희망 일정을 알려주세요.</p><p class="notice">입력 내용을 이메일로 작성합니다. 메일 앱에서 직접 발송해야 전달되며, 상담 후 일정을 확정합니다.</p><form id="inquiry-form"><div class="form-grid"><label class="field">관심 강의<select name="강의">${courses.map((c,i)=>`<option${i===index?' selected':''}>${c.name}</option>`).join('')}</select></label><label class="field">교육 대상<select name="교육 대상" required><option value="">선택해 주세요</option>${[...audiences.map(a=>a[0]),'기타'].map((a,i)=>`<option${i===audience?' selected':''}>${a}</option>`).join('')}</select></label><label class="field">이름 / 담당자 *<input name="이름" autocomplete="name" maxlength="50" required></label><label class="field">기관 / 소속<input name="소속" autocomplete="organization" maxlength="100"></label><label class="field">연락처 *<input name="연락처" type="tel" autocomplete="tel" maxlength="30" required></label><label class="field">이메일<input name="이메일" type="email" autocomplete="email" maxlength="100"></label><label class="field">희망 일정<input name="희망 일정" type="date"></label><label class="field">예상 인원<input name="예상 인원" maxlength="30" placeholder="예: 20명 또는 미정"></label><label class="field full">문의 내용<textarea name="문의 내용" maxlength="1500" placeholder="희망 주제, 교육 목적, 장소 등을 알려주세요. 민감정보나 기관 내부 기밀은 입력하지 마세요."></textarea></label></div><label class="checkbox"><input type="checkbox" required>입력한 내용이 이메일 작성에 사용되며, 직접 발송해야 전달된다는 점을 확인했습니다.</label><div class="form-actions"><button class="button" type="submit">이메일 작성하기 ↗</button><button class="text-button" id="copy-inquiry" type="button">내용 복사하기</button></div><p class="form-status" role="status" aria-live="polite"></p></form>`);
const form=document.querySelector('#inquiry-form'),status=form.querySelector('.form-status');
const message=()=>`${title}\n\n`+[...new FormData(form).entries()].map(([k,v])=>`${k}: ${String(v).trim()||'미정'}`).join('\n');
form.addEventListener('submit',e=>{e.preventDefault();location.href=`mailto:e_ikenkon@hanmail.net?subject=${encodeURIComponent('[일의다음] '+title)}&body=${encodeURIComponent(message())}`;status.textContent='메일 앱에서 수신자와 내용을 확인하고 발송해 주세요. 앱이 열리지 않으면 내용을 복사하여 e_ikenkon@hanmail.net으로 보내주세요. 아직 접수된 상태는 아닙니다.'});
document.querySelector('#copy-inquiry').addEventListener('click',async()=>{if(!form.reportValidity())return;try{await navigator.clipboard.writeText(message());status.textContent='내용을 복사했습니다. e_ikenkon@hanmail.net으로 직접 보내주세요.'}catch{status.textContent='복사 권한이 없어 자동 복사를 할 수 없습니다. 이메일 작성 버튼을 이용하거나 전화로 문의해 주세요.'}});
}

